# Generated by Django 4.1.4 on 2022-12-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querytopredict',
            name='img',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
