# Generated by Django 4.1.4 on 2022-12-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_querytopredict_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querytopredict',
            name='slug',
        ),
        migrations.AddField(
            model_name='querytopredict',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
